services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    App\Casing\FormInterface\Contribution\CaseFormContributionInterface:
      tags: ['casing.form_contribution']

  App\Casing\ServiceInterface\Resolver\PurchasedProductSubjectResolverInterface:
    alias: App\Casing\Service\Resolver\Ordering\PurchasedProductSubjectResolver

  App\Casing\ServiceInterface\Resolver\ServicePaymentSubjectResolverInterface:
    alias: App\Casing\Service\Resolver\Paying\ServicePaymentSubjectResolver

  App\Casing\ServiceInterface\Resolver\LeadSubjectResolverInterface:
    alias: App\Casing\Service\Resolver\Relating\LeadSubjectResolver

  App\Casing\RepositoryInterface\CaseOutboxMessageRepositoryInterface:
    alias: App\Casing\Repository\CaseOutboxMessageRepository

  App\Casing\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/DTO/'
      - '../src/Entity/'
      - '../src/Enum/'
      - '../src/Value/'
      - '../src/FormInterface/'
      - '../src/RepositoryInterface/'
      - '../src/ServiceInterface/'

  App\Casing\Service\Form\CaseFormContributionRegistry:
    arguments:
      $providers: !tagged_iterator casing.form_contribution
