services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    App\Casing\FormInterface\Contribution\CaseFormContributionInterface:
      tags: ['casing.form_contribution']

  App\Casing\ResolverInterface\Ordering\CasePurchasedProductSubjectResolverInterface:
    alias: App\Casing\Resolver\Ordering\CasePurchasedProductSubjectResolver

  App\Casing\ResolverInterface\Paying\CaseServicePaymentSubjectResolverInterface:
    alias: App\Casing\Resolver\Paying\CaseServicePaymentSubjectResolver

  App\Casing\ResolverInterface\Relating\CaseLeadSubjectResolverInterface:
    alias: App\Casing\Resolver\Relating\CaseLeadSubjectResolver

  App\Casing\RepositoryInterface\CaseDraftRepositoryInterface:
    alias: App\Casing\Repository\CaseDraftRepository

  App\Casing\RepositoryInterface\CaseRepositoryInterface:
    alias: App\Casing\Repository\CaseRepository

  App\Casing\RepositoryInterface\CaseOutboxMessageRepositoryInterface:
    alias: App\Casing\Repository\CaseOutboxMessageRepository

  App\Casing\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/DTO/'
      - '../src/Entity/'
      - '../src/Enum/'
      - '../src/Value/'
      - '../src/FormInterface/'
      - '../src/RepositoryInterface/'
      - '../src/ResolverInterface/'
      - '../src/ServiceInterface/'

  App\Casing\Service\Form\CaseFormContributionRegistry:
    arguments:
      $providers: !tagged_iterator casing.form_contribution
